USE pureskin_clinic;

-- Seed admin, doctors, patient users
-- NOTE: Replace the password hashes with real bcrypt hashes generated by the backend.

INSERT INTO Users (name, email, password, role) VALUES
('Admin User', 'admin@pureskin.local', '$2a$10$REPLACE_WITH_ADMIN_HASH', 'admin'),
('Dr. Alice Derm', 'alice.derm@pureskin.local', '$2a$10$REPLACE_WITH_DOCTOR_HASH', 'doctor'),
('Dr. Bob Skin', 'bob.skin@pureskin.local', '$2a$10$REPLACE_WITH_DOCTOR_HASH', 'doctor'),
('Test Patient', 'patient@pureskin.local', '$2a$10$REPLACE_WITH_PATIENT_HASH', 'patient');

-- Doctors (link to doctor users by user_id)
INSERT INTO Doctors (user_id, specialization) VALUES
((SELECT id FROM Users WHERE email = 'alice.derm@pureskin.local'), 'Dermatology'),
((SELECT id FROM Users WHERE email = 'bob.skin@pureskin.local'), 'Cosmetic Dermatology');

-- Patient profile
INSERT INTO Patients (user_id, phone, date_of_birth, address, general_health) VALUES
((SELECT id FROM Users WHERE email = 'patient@pureskin.local'),
 '+1-555-000-0000',
 '1990-01-01',
 '123 Test Street, Test City',
 'Generally healthy');

-- Basic medical record for test patient
INSERT INTO MedicalRecords (patient_id, skin_type, complaints, dermatological_history, allergies, current_medications, pregnancy_status, notes)
VALUES (
  (SELECT p.id FROM Patients p JOIN Users u ON p.user_id = u.id WHERE u.email = 'patient@pureskin.local'),
  'Combination',
  'Occasional acne and dryness',
  'No major dermatological conditions',
  'No known allergies',
  'None',
  'N/A',
  'Initial seeded record for testing'
);

-- Products
INSERT INTO Products (name, description, category, price, stock, image_url) VALUES
('Hydrating Cleanser', 'Gentle hydrating facial cleanser for daily use.', 'Skin Care', 19.99, 50, 'https://via.placeholder.com/300x300?text=Cleanser'),
('SPF 50 Sunscreen', 'Broad-spectrum sunscreen suitable for sensitive skin.', 'Skin Care', 24.99, 80, 'https://via.placeholder.com/300x300?text=Sunscreen'),
('Hair Strength Serum', 'Serum to promote stronger, healthier hair.', 'Hair Care', 29.99, 40, 'https://via.placeholder.com/300x300?text=Hair+Serum'),
('Nourishing Body Lotion', 'Deeply moisturizing body lotion.', 'Body Care', 17.50, 60, 'https://via.placeholder.com/300x300?text=Body+Lotion');


